### ISSUE TITLE
database_username management on Mysql RDS on Flexible Engine

### ISSUE THREAD

**Issue by yeplaa** [huaweicloud/huaweicloud-service-broker#67]
Hello,

From Openshift Origin, i use huaweicloud-service-broker for provision RDS Mysql 5.7.21 on Flexible Engine OBS. The provisioning works.

As indicated on the doc, i tried to modify the **database_username** in the  config.json. But I see that the user by default (root) is still created, and not my user.

Bellow my configuration : 

                        {
                            "id": "839f4458-309a-4e05-a069-807e950cf6da",
                            "name": "5.7.21",
                            "description": "RDS MySQL 5.7.21",
                            "metadata": {
                                "parameters": {
                                    "datastore_type": "MySQL",
                                    "datastore_version": "5.7.21",
                                    "speccode": "rds.mysql.s1.xlarge",
                                    "volume_type": "COMMON",
                                    "volume_size": 100,
                                    "availability_zone": "eu-west-0a",
                                    "vpc_id": "45ca053a-194c-4538-8265-0512c691d363",
                                    "subnet_id": "b3f34e39-4487-4c9c-b0e2-e30630835822",
                                    "security_group_id": "e37131c1-5464-4fde-991e-b0dd5c8b50e7",
                                    "database_username": "essai"
                                }
                            }
                        }

I feel that the functionality is not functional. Can you see please?

Thank's
Loïc

**Comment by edisonxiang** [comment]
@yeplaa Yeah. As the orange web console shows, currently we only support ```root``` user in the mysql and ```rdsuser``` in the sqlserver. So we just put this parameter in the ```config.json```, and not put it in the usage document.  We could use this parameter once the rds supports more database users. I have updated the configuration to make some notes for this.

https://github.com/huaweicloud/huaweicloud-service-broker/blob/master/docs/configuration/rds-mysql.md

Thanks @yeplaa :)

**Comment by yeplaa** [comment]
Hi @edisonxiang , thank's for your reoly :) I close this issue.

**Comment by yeplaa** [comment]
Hi @edisonxiang , thank's for your reoly :) I close this issue.
