### ISSUE TITLE
Deploying an Instance from the Openshift Web Interface Catalog

### ISSUE THREAD

**Issue by yeplaa** [huaweicloud/huaweicloud-service-broker#68]
Hello,

From Openshift Origin, i use huaweicloud-service-broker for provision RDS Mysql on Flexible Engine OBS. The provisioning works by cli with the **serviceInstance** yaml file. 

Now, I'd like to deploy an instance from the catalog accessible by the Openshift GUI.
The item (RDS Mysql for example) is availabe from the catalog but it's it does not seem possible to offer users the filling of fields associated with the provisioning parameters (see for example the parameters <https://github.com/huaweicloud/huaweicloud-service-broker/blob/master/docs/usage/rds-mysql.md>)

Indeed, like the Openshift *template-service-broker*, I would like to enter the values of the parameters on the *configuration* menu as on this example :  

![parameters_by_gui](https://user-images.githubusercontent.com/1431047/49793974-c03bb580-fd36-11e8-9350-fabf11f3a43f.png)

Is it possible now or is it planned?

Thank's
Loïc

**Comment by edisonxiang** [comment]
@yeplaa Thanks your issue about this.
It seems like there are some differences between cloud foundry and openshift.
I will find the reason and solve this issue.

**Comment by edisonxiang** [comment]
@yeplaa I have made [a commit](https://github.com/huaweicloud/huaweicloud-service-broker/commit/bcfd07ea9f788c9be11dc4ee3f4b85db5acf0af8) to support deploying an instance by the Openshift GUI, and the docker image (quay.io/huaweicloud/huaweicloud-service-broker) has also been updated. 

Could you redeploy service broker in the OpenShift Cluster from [this step](https://github.com/huaweicloud/huaweicloud-service-broker#3-creating-service-in-openshift-cluster) and test it again by the Openshift GUI? 

Thanks very much!

**Comment by yeplaa** [comment]
Thank's @edisonxiang four your action.  I would test in January the feature and I will give you a feedback.

**Comment by edisonxiang** [comment]
@yeplaa Got it. Merry Christmas:)

**Comment by yeplaa** [comment]
Hi @edisonxiang,

Thank's for your actions. Now, I can deploy an instance from the catalog accessible by the Openshift GUI for RDS and DCS.

2 query : 

- For DCS, it is necessary to set an value for "availability_zone"  while yet the value has been set in the config.json file.         
Bellow the errors of api call : 

        "error_code": "dcs.03.0001",
        "fail_reason": "CreateVMTask-fail:Create VM error"

Is it normal? 
If i set the value when i deploy from the GUI, the provisioning is OK.

- Is it possible to choose the display order of the parameters or hide some parameters from the GUI template by the configuration of config.json file? Or is this configuration, this choices are hard coded into the huawei-service-broker docker image?

Thank's 
Loic

**Comment by yeplaa** [comment]
Hi @edisonxiang,

When i wish deploy a RDS Mysql HA with the by the Openshift GUI, I have the impression that there is a problem. 

Bellow the error of Hauwei Broker : 

      "data":{"error":
      "provision rds instance failed. Error: Missing input for argument [Enable]"

Bellow the full log  : 

 {"timestamp":"1547628458.591950655","source":"ServiceBroker","message":"ServiceBroker.provision rds instance opts: {\"name\":\"essai6\",\"dat
astore\":{\"type\":\"MySQL\",\"version\":\"5.7.21\"},\"flavorRef\":\"6ba2c53b-386b-41bf-bc70-72cc78a867a6\",\"volume\":{\"type\":\"COMMON\",\
"size\":100},\"region\":\"eu-west-0\",\"availabilityZone\":\"eu-west-0a\",\"vpc\":\"45ca053a-194c-4538-8265-0512c691d363\",\"nics\":{\"subnet
Id\":\"b3f34e39-4487-4c9c-b0e2-e30630835822\"},\"securityGroup\":{\"id\":\"e37131c1-5464-4fde-991e-b0dd5c8b50e7\"},\"backupStrategy\":{\"star
tTime\":\"00:00:00\"},\"dbRtPd\":\"tbx3R7T5!\",\"ha\":{\"enable\":false,\"replicationMode\":\"semisync\"}}","log_level":0,"data":{}}
{"timestamp":"1547628458.592038631","source":"ServiceBroker","message":"ServiceBroker.provision.unknown-error","log_level":2,"data":{"error":
"provision rds instance failed. Error: Missing input for argument [Enable]","instance-details":{"service_id":"275f3e0b-86fd-4303-946c-171374d
29150","plan_id":"839f4458-309a-4e05-a069-807e950cf6da","organization_guid":"7d306fb5-ec26-11e8-aea1-0a580a8000b0","space_guid":"f2ec1eb1-13f
8-11e9-b5f4-fa163ea276c9","context":{"clusterid":"7d306fb5-ec26-11e8-aea1-0a580a8000b0","namespace":"essai","platform":"kubernetes"},"paramet
ers":{"database_password":"tbx3R7T5!","ha_enable":"true","ha_replicationmode":"semisync","name":"essai6","speccode":"rds.mysql.s1.large.ha"}}
,"instance-id":"c1af35ae-196a-11e9-800e-0a580a8000c2","session":"1459"}}

On The Gui, i choose the true value in the dropdown menu of ha_enable parameter but maybe the value is not taken into account as indicated into the log : 

          \"ha\":{\"enable\":false

do you have an idea? 

Thank's
Loïc

**Comment by edisonxiang** [comment]
Hi @yeplaa I have submit [a commit](https://github.com/huaweicloud/huaweicloud-service-broker/commit/a87ffc280e5483738f318d43e084a2e4d30c2713) to fix these issues.
Fix including the following parts:
* could not set ha=true when creating RDS Mysql HA instance in the UI.
* auto fill with the default values(e.g. availability_zones) like the template-service-broker in the UI.

The docker image is updated, Thanks very much.
