### ISSUE TITLE
Empty operation bug in Provision/Bind request

### ISSUE THREAD

**Issue by leonwanghui** [huaweicloud/huaweicloud-service-broker#69]
## Problem description
Currently we are working on integrating this project into [FusionStage](https://developer.huawei.com/ict/en/site-paas) platform, and we found that when handling async Provision/Bind request, broker would return an empty value for `operation` field, which could cause some errors in the platform.

## Proposal
Suggest return a no-empty value in `operation` field.

**Comment by edisonxiang** [comment]
Thanks.
We can reopen this issue if FusionStage support the feature:)
