### ISSUE TITLE
Encryption of credentiels in the Mysql database

### ISSUE THREAD

**Issue by yeplaa** [huaweicloud/huaweicloud-service-broker#73]
Hello,

From Openshift Origin, i use huaweicloud-service-broker for provision RDS Mysql and DCS Redis on Flexible Engine OBS.

Currently, all username, password of provisioned databases are stored in clear in the backing mysql database. If the backing Mysql database is corrupted, access to all other provisioned databases is possible.

Is it possible to increase the security on this part with a username / password encryption for example?

Thank's
Loïc

**Comment by edisonxiang** [comment]
Hello @yeplaa,
Thanks your suggestion for security.
I am planing to add ```base64``` encoding for the `username` and `password` of provisioned databases in the backing mysql database, as the openshift ```secret``` does that in the same way.

What do you think about that?

**Comment by edisonxiang** [comment]
Thanks @yeplaa I will find some ways to fix this issue:)
