### ISSUE TITLE
Create rds postgres with replica on Flexible Engine

### ISSUE THREAD

**Issue by T0FFF** [huaweicloud/huaweicloud-service-broker#85]
Hello,

I try to provision a rds postgres cluster thanks to the broker but if I want a deployment with replication, I cannot do it.

With Cloud Foundry:
`
cf create-service rds-postgresql 9.6.5 instanceName -c '{"name": "RDSPostgreSQL-tmp", "database_password": "xxxxxxx", "ha_replicationmode": "sync" , "ha_enable": true}'
=>
Service broker error: provision rds instance failed. Error: Invalid request due to incorrect syntax or missing required parameters.
FAILED
`

https://github.com/huaweicloud/huaweicloud-service-broker/blob/master/docs/usage/rds-postgresql.md
What is the correct syntax ?

**Comment by duckShooter** [comment]
I'm having the same issue! 
Actually, this issue is presented when any parameter other than "user" and "database_password" is provided. 
For example when I try to add a "database_port" parameter I get the same error

**Comment by zhongjun2** [comment]
@T0FFF Cloud you set specode to "rds.db.s1.xlarge.ha" ? Cloud you put your logs on this?



speccode | string | N | Indicates the resource specifications code. Use rds.pg.s1.xlarge as an example. rds indicates RDS, pg indicates the DB engine, and s1.xlarge indicates the performance specification. The parameter containing rr indicates the read replica specifications. The parameter not containing rr indicates the single or primary/standby DB instance specifications. If you enable HA, the suffix .ha need be added to the DB instance name. For example, the DB instance name is rds.db.s1.xlarge.ha. The default value is in the config file.
-- | -- | -- | --

**Comment by T0FFF** [comment]
@zhongjun2, With speccode, I've this message:
`
Creating service instance postgres-rds-test-app-service-ocb-testCLZ-tmp in org cf-skc / space clecoz as clecoz...
Service broker error: Returned no flavor Id
FAILED
`

**Comment by zhongjun2** [comment]
@T0FFF  The speccode should set to one value for HA.  Such as "rds.db.s1.large.ha" or ".........ha". You could get one speccode value in Flexible Engine doc, or  pod log "kubectl logs  service-....-0 ". It will list all flavors(specode) in log.

**Comment by T0FFF** [comment]
Thanks @zhongjun2, It works !

**Comment by zhongjun2** [comment]
@T0FFF You are welcome.
